# Halloween and candy

## Libraries


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_auc_score,roc_curve
from sklearn.model_selection import train_test_split, cross_val_score

## Data

source: [The Ultimate Halloween Candy Power Ranking](https://www.kaggle.com/datasets/fivethirtyeight/the-ultimate-halloween-candy-power-ranking)

In [2]:
candy_df = pd.read_csv("candy-data.csv")
candy_df.head()

competitorname  chocolate  fruity  caramel  peanutyalmondy  nougat  \
0      100 Grand          1       0        1               0       0   
1   3 Musketeers          1       0        0               0       1   
2       One dime          0       0        0               0       0   
3    One quarter          0       0        0               0       0   
4      Air Heads          0       1        0               0       0   

   crispedricewafer  hard  bar  pluribus  sugarpercent  pricepercent  \
0                 1     0    1         0         0.732         0.860   
1                 0     0    1         0         0.604         0.511   
2                 0     0    0         0         0.011         0.116   
3                 0     0    0         0         0.011         0.511   
4                 0     0    0         0         0.906         0.511   

   winpercent  
0   66.971725  
1   67.602936  
2   32.261086  
3   46.116505  
4   52.341465

In [3]:
candy_df.columns


Index(['competitorname', 'chocolate', 'fruity', 'caramel', 'peanutyalmondy',
       'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'sugarpercent',
       'pricepercent', 'winpercent'],
      dtype='object')

In [4]:
candy_df.drop("competitorname", inplace = True, axis=1)
data = candy_df.copy(deep = True)

## Analysis of the data using Logistic regression 

In this example, we train and test a logistic regression against the whole dataset. It is an analysis to establish whether a logistic relationship may exist with the data. We complete two analysis one with the chocolate and  nougat content.

We use a logistic regression; the data is binary.

### Chocolate

Define X and Y data

In [5]:
y = data.chocolate.values
X = data.drop(["chocolate"], axis = 1)

In [6]:
X

fruity  caramel  peanutyalmondy  nougat  crispedricewafer  hard  bar  \
0        0        1               0       0                 1     0    1   
1        0        0               0       1                 0     0    1   
2        0        0               0       0                 0     0    0   
3        0        0               0       0                 0     0    0   
4        1        0               0       0                 0     0    0   
..     ...      ...             ...     ...               ...   ...  ...   
80       1        0               0       0                 0     0    0   
81       1        0               0       0                 0     1    0   
82       1        0               0       0                 0     0    0   
83       0        1               0       0                 0     1    0   
84       0        0               0       0                 1     0    0   

    pluribus  sugarpercent  pricepercent  winpercent  
0          0         0.732         0.860   66.971725  
1          0         0.604         0.511   67.602936  
2          0         0.011         0.116   32.261086  
3          0         0.011         0.511   46.116505  
4          0         0.906         0.511   52.341465  
..       ...           ...           ...         ...  
80         0         0.220         0.116   45.466282  
81         0         0.093         0.116   39.011898  
82         1         0.313         0.313   44.375519  
83         0         0.186         0.267   41.904308  
84         1         0.872         0.848   49.524113  

[85 rows x 11 columns]

In [7]:
y

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1])

We complete some model fitting; it could be consider as a training phase. 

In [8]:
log_reg = LogisticRegression()
log_reg_model = log_reg.fit(X,y)
log_reg_model

LogisticRegression()

Show the model intercept within the data and the coefficient. 

In [9]:
log_reg_model.intercept_      # constant value|
log_reg_model.coef_ 

array([[-2.52284281, -0.10279195, -0.16146574, -0.07635225,  0.39014556,
        -0.11493683,  0.82717389, -0.29839462, -0.10920639,  0.57972453,
         0.12082792]])

The confusion matrix shows a small number of True and False negatives. 

In [10]:
y_pred = log_reg_model.predict(X)
y_pred

array([1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1])

In [11]:
accuracy_score(y, y_pred)

0.9176470588235294

__Evaluation:__
With an accuracy greater than 0.9, we could surmise the content of chocolate may have a logistic relationship and price, sugar, and popularity

### Nougat
Define the data

In [12]:
data = candy_df.copy(deep = True)
y = data.nougat.values
X = data.drop(["nougat"], axis = 1)

In [13]:
log_reg = LogisticRegression()
log_reg_model = log_reg.fit(X,y)
log_reg_model

LogisticRegression()

In [14]:
log_reg_model.intercept_      # constant value|
log_reg_model.coef_ 

array([[ 0.10937061, -0.56555099,  0.78899867,  0.34382824, -0.97445671,
        -0.25341534,  1.60527718, -0.78397339,  0.30097625, -0.23575434,
         0.01156065]])

In [15]:
log_reg_model.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
accuracy_score(y, y_pred)

0.6823529411764706

__Evaluation:__ With an accuracy approximated to 0.7 (1 s.f), the level of likelyhood  the content of nougat may have a logistic relationship against price, sugar, and popularity is not strong.

# Classification using Logistic regression
In this example, we train and test a logistic regression against the whole dataset. It is an analysis to establish whether a logistic relationship may exist with the data. We complete two analysis one with the chocolate and nougat content.

We use a logistic regression; the data is binary. We use a cross validation where we split the data in a train and a test dataset.

## Chocolate
We repeat the same steps. 
1.  define X and y
2.  split in a training and testing datasets
3.  train the model using the training datasets
4.  validate the model using the testing dataset

In [17]:
data = candy_df.copy(deep = True)
y = data.chocolate.values
X = data.drop(["chocolate"], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.40, 
                                                    random_state = 42)

In [18]:
log_reg = LogisticRegression()
log_reg_model = log_reg.fit(X_train,y_train)
log_reg_model

LogisticRegression()

In [19]:
log_reg_model.intercept_      # constant value|
log_reg_model.coef_ 

array([[-1.72204171, -0.03672871, -0.23070348, -0.1182813 ,  0.10166805,
        -0.14475021,  0.28561458, -0.28218058, -0.43644362,  0.43665275,
         0.13373461]])

In [20]:
y_pred_train  = log_reg_model.predict(X_train)
confusion_matrix(y_train, y_pred_train)  

array([[28,  2],
       [ 5, 16]])

In [21]:
accuracy_score(y_train, y_pred_train)

0.8627450980392157

In [22]:
y_pred  = log_reg_model.predict(X_test)
confusion_matrix(y_test, y_pred)          # confussion matrix

array([[17,  1],
       [ 1, 15]])

In [23]:
accuracy_score(y_test, y_pred)

0.9411764705882353

In [24]:
cross_val_score(log_reg_model, X_test, y_test, cv = 10)

array([0.75, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ])

In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        18
           1       0.94      0.94      0.94        16

    accuracy                           0.94        34
   macro avg       0.94      0.94      0.94        34
weighted avg       0.94      0.94      0.94        34



__Evaluation:__
The logistic regression model has approximately 0.94 accuracy of predictions on unseen data. The error has been reduced from the training to the unseen data. Perhaps the distribution of the data have affected the classification. Further classification needs to be completed using a larger dataset.

## Nougat
We complete the  steps.
1. define X and y
2. split in a training and testing datasets
3. train the model using the training datasets
4. validate the model using the testing dataset

In [26]:
data = candy_df.copy(deep = True)
y = data.nougat.values
X = data.drop(["nougat"], axis = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.40, 
                                                    random_state = 42)

In [27]:
log_reg = LogisticRegression()
log_reg_model = log_reg.fit(X_train,y_train)
log_reg_model

LogisticRegression()

In [28]:
log_reg_model.intercept_      # constant value|
log_reg_model.coef_ 

array([[ 0.06412272, -0.4021222 ,  0.62462274,  0.63129844, -0.63059859,
        -0.24767532,  1.50539417, -0.7373725 ,  0.22905753, -0.09493203,
         0.01741147]])

In [29]:
y_pred_train  = log_reg_model.predict(X_train)
confusion_matrix(y_train, y_pred_train)  

array([[46,  0],
       [ 4,  1]])

In [30]:
accuracy_score(y_train, y_pred_train)

0.9215686274509803

In [31]:
y_pred  = log_reg_model.predict(X_test)
confusion_matrix(y_test, y_pred)  

array([[32,  0],
       [ 1,  1]])

In [32]:
accuracy_score(y_test, y_pred)

0.9705882352941176

In [33]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        32
           1       1.00      0.50      0.67         2

    accuracy                           0.97        34
   macro avg       0.98      0.75      0.83        34
weighted avg       0.97      0.97      0.97        34



__Evaluation:__ 
    
The model fitting has an approximated 0.08 error.  The prediction with unseen data has improved to an accuracy of .97.

# Thank you 
I would like to thank the author of the[The Ultimate Halloween Candy Power Ranking](https://www.kaggle.com/datasets/fivethirtyeight/the-ultimate-halloween-candy-power-ranking). Further analysis and description about the data can be found on Kaggle.